# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
   config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "fm.local"
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "private_network", ip: "10.55.55.2"
#    virtualbox__intnet: true
  config.vm.provision :shell, path: "bootstrap.sh"
end
